Averaging to adding
WilmerLab/sensor_array_mof_adsorption pull request #11
Opened 2017-10-20 20:42 UTC by JennaGustafson

2017-11-09 16:24 UTC, paulboone requested changes
Looks good. You had some commenting in / out of code which should never really be committed. Can you check those and make sure they were actually removed?

2017-11-09 16:24 UTC, paulboone commented on execute_process_mass_data.py
> +# combined_kld, ordered_by_gas, best_arrays, ordered_kld_w_array, average_kld = choose_best_arrays(gases, kl_divergence)
commented out code

2017-11-09 16:24 UTC, paulboone commented on execute_process_mass_data.py
>  # plot_binned_pmf_array(gases, list_of_arrays, create_bins_results, bin_compositions_results)
generally the word "squash" in a commit message indicates that you forgot to actually squash

2017-11-09 16:24 UTC, paulboone commented on execute_process_mass_data.py
> +# write_output_data('saved_results/ordered_by_gas_kld_%s.csv' % (datetime.now().strftime("%Y_%m_%d__%H_%M_%S")), ordered_by_gas)
commented out code

2017-12-20 16:40 UTC, JennaGustafson commented
There were two lines of code commented out in the final version of process_mass_data.py, so I deleted them (they are not used) and squashed that commit further back where I initially committed the commented out code. The final version looks better.

2018-01-19 17:51 UTC, paulboone approved these changes

2018-01-19 17:51 UTC, merged