Henrys work
WilmerLab/sensor_array_mof_adsorption pull request #19
Opened 2020-06-16 16:32 UTC by birdday

This is the somewhat massive set of codes used to (1) determine Henry's coefficients from adsorption data, (2) design arrays from the Henry's coefficients, and (3) predict sample compositions with the new algorithmic procedure. I tried to clean up the commits as best as I could, some are still a bit messy, or just large chunks of new code, but overall I'd say it's a lot cleaner than previous PRs, so hopefully it won't take us too long.

2020-07-13 13:58 UTC, paulboone requested changes
let's talk this over after group meeting if you have time

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis.py
> +from brute_force_analysis import (
Changes need to be atomic. You can't change the module name without renaming the module.

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis.py
> +exp_data = data['exp_data']
I'm glad this is no longer hard coded.

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis.py
> +filepath = 'config_files/process_config.sample.yaml'
why are we loading from a .sample file?

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_genetic_algorithm_analysis.py
> +filepath = 'config_files/process_config.sample.yaml'
why are we loading from a sample file?

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_genetic_algorithm_analysis.py
> +exp_data = data['exp_data']
this method seems like a near duplicate of the above. Can they be combined? Can we have one settings load? Check out how I did my settings loading for the htsohm project: https://github.com/paulboone/htsohm/blob/pmaster/htsohm/config.py

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_genetic_algorithm_analysis.py
> +from genetic_algorithm_analysis import *
again, changes must be atomic. You have to rename the directory at the same time.

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis.py
>      plot_binned_array_pmf_data)
this many imports is a sign you either should be using a namespace, i.e. calling these as brute_force_analysis.choose_arrays, or maybe the method that is calling all these should also be in the brute_force_analysis namespace

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +        bin_points.append(np.linspace(lower_lim, upper_lim, num=num_bins+1, endpoint=True))
I need you to walk me through this commit ca6e013a5c11488af46f5a14a5dba656f585235b

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +        C_out = np.round(c[i]*100,3)
variables are not normally capitalized: https://www.python.org/dev/peps/pep-0008/#id45

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +    plt.savefig('/Users/brian_day/Desktop/triplots/%s.png' % array_id, bbox_inches='tight')
shouldn't have hard code urls in the code base. usually, just saving them to the current directory is good.

2020-07-13 13:58 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +    plt.savefig("/Users/brian_day/Desktop/binned_pmf_figs/%s.png" % (array))
hard coded path will break for everybody else

2020-07-13 13:58 UTC, paulboone commented on sensor_array/helper/plot_GA_results_redo.py
> -import numpy as np
lets talk about this commit 9c54fbcd01fce9f182a5518f13d28c212bff1c1c

2020-07-16 14:55 UTC, paulboone reviewed
yes yes yes! This is much, much better. I still need to go through it with you, since there is a LOT of new code. Let's go over it over zoom.

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +        bin_points.append(np.linspace(lower_lim, upper_lim, num=num_bins+1, endpoint=True))
Can you explain why we are using append here?

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +            if type == 'percent':
use elif

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +            if type == 'mass':
if there is a reference for these, might be helpful to have it here so somebody could verify where the math comes from.

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +def create_comp_list(simulated_data, mof_list, gases):
walk me through this over phone: 2e0ea26925572

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis_singlearray_allexp.py
> +    plot_binned_array_pmf_data)
this is screaming out for something like:

```
import brute_force_analysis as bfa
bfa.create_bins
# eetc
```

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/brute_force_analysis.py
> +def calculate_all_arrays_list(mof_list, num_mofs):
let's review this one over phone 8203b03d94a9280558401c7437fa573e870263ff

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis.py
> +from genetic_algorithm_analysis import read_GA_results_messy
while this is technically an atomic commit, it doesn't functionally do anything, so this would typically be added elsewhere when this was needed

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/genetic_algorithm_analysis.py
> +def moving_average_smooth(sim_results_import, mof_list, gases, comp_list, mole_fractions, num_points=1):
is this a duplicate of code elsewhere?

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/genetic_algorithm_analysis.py
> +                    mof_temp_dict['PMF_Exact'] = norm_probs_exact[index]
outputting the range and the exact info doesn't look like it is part of "Added multiple error types for probability to GA code." should either be a separate commit or the commit message should include something about this.

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/execute_genetic_algorithm_analysis.py
> +num_runs = 1
commit message is vague and doesn't indicate these changes to the runs / array_size_vect

2020-07-16 14:55 UTC, paulboone commented on sensor_array/helper/generate_compositions.py
> +def create_uniform_comp_list(gases, gas_limits, spacing, filename=None, imply_final_gas_range=True, imply_final_gas_spacing=False, filter_for_1=True, round_at=None):
review this commit: 32585ab8

2020-07-16 14:55 UTC, paulboone commented on sensor_array/analysis/array_analysis_SVD.py
> +
review this commit: 37a7868

2020-07-16 14:58 UTC, birdday commented
Okay great thanks! Sorry this is the codeI didn’t put much effort into rebasing because it wasn’t too important anymore, but gald you didn’t waste much time on it before.

I’m free all day today pretty much, and most of tomorrow, except for a short meeting with Xin around 11. Let me know when works for you.

From: Paul Boone <notifications@github.com>
Reply-To: WilmerLab/sensor_array_mof_adsorption <reply@reply.github.com>
Date: Thursday, July 16, 2020 at 10:55 AM
To: WilmerLab/sensor_array_mof_adsorption <sensor_array_mof_adsorption@noreply.github.com>
Cc: Brian Day <22bday@gmail.com>, Author <author@noreply.github.com>
Subject: Re: [WilmerLab/sensor_array_mof_adsorption] Henrys work (#19)


@paulboone commented on this pull request.

yes yes yes! This is much, much better. I still need to go through it with you, since there is a LOT of new code. Let's go over it over zoom.

________________________________

In sensor_array/analysis/brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455435857>:

> @@ -320,7 +329,7 @@ def create_bins(gases, num_bins, mof_list, element_pmf_results):

         # Jenna Bins

         # lower_lim = lower_comp

         # upper_lim = upper_comp + (upper_comp-lower_comp)/(num_bins)

-        bin_points = np.linspace(lower_lim, upper_lim, num=num_bins+1, endpoint=True)

+        bin_points.append(np.linspace(lower_lim, upper_lim, num=num_bins+1, endpoint=True))

Can you explain why we are using append here?

________________________________

In sensor_array/analysis/brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455436495>:

> @@ -191,9 +191,14 @@ def calculate_element_pmf(exp_results_full, sim_results_full, mof_list, stdev, m

         for mass_exp in all_masses_exp:

             probs_range = []

             probs_exact = []

-            a, b = 0, float(max(all_masses_sim)) * (1 + mrange)

-            mu, sigma = float(mass_exp), float(stdev)*float(mass_exp)

-            alpha, beta = ((a-mu)/sigma), ((b-mu)/sigma)

+            if type == 'mass':

+                a, b = 0, 2*float(max(all_masses_sim))

+                mu, sigma = float(mass_exp), float(stdev)

+                alpha, beta = ((a-mu)/sigma), ((b-mu)/sigma)

+            if type == 'percent':

use elif

________________________________

In sensor_array/analysis/brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455437258>:

> @@ -191,9 +191,14 @@ def calculate_element_pmf(exp_results_full, sim_results_full, mof_list, stdev, m

         for mass_exp in all_masses_exp:

             probs_range = []

             probs_exact = []

-            a, b = 0, float(max(all_masses_sim)) * (1 + mrange)

-            mu, sigma = float(mass_exp), float(stdev)*float(mass_exp)

-            alpha, beta = ((a-mu)/sigma), ((b-mu)/sigma)

+            if type == 'mass':

if there is a reference for these, might be helpful to have it here so somebody could verify where the math comes from.

________________________________

In sensor_array/analysis/brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455437671>:

> @@ -135,6 +136,140 @@ def import_simulated_data(sim_results_import, mof_list, mof_densities, gases):

     return sim_results_full





+def create_comp_list(simulated_data, mof_list, gases):

walk me through this over phone: 2e0ea26<https://github.com/WilmerLab/sensor_array_mof_adsorption/commit/2e0ea26925572b8af3681a10b58acbb5d4e79897>

________________________________

In sensor_array/analysis/execute_brute_force_analysis_singlearray_allexp.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455438194>:

> +    calculate_all_arrays_list,

+    calculate_all_arrays,

+    calculate_single_array_kld,

+    create_bins,

+    create_comp_set_dict,

+    bin_compositions,

+    bin_compositions_single_array,

+    calculate_kld,

+    choose_arrays,

+    assign_array_ids,

+    save_element_pmf_data,

+    save_unbinned_array_pmf_data,

+    plot_element_mass_data,

+    plot_unbinned_array_pmf_data,

+    save_binned_array_pmf_data,

+    plot_binned_array_pmf_data)

this is screaming out for something like:

import brute_force_analysis as bfa

bfa.create_bins

# eetc

________________________________

In sensor_array/analysis/brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455438654>:

> @@ -391,6 +391,16 @@ def calculate_array_pmf(mof_array, element_pmf_results):

     return single_array_pmf_results





+def calculate_all_arrays_list(mof_list, num_mofs):

let's review this one over phone 8203b03<https://github.com/WilmerLab/sensor_array_mof_adsorption/commit/8203b03d94a9280558401c7437fa573e870263ff>

________________________________

In sensor_array/analysis/execute_brute_force_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455438955>:

> @@ -35,6 +35,7 @@

     plot_unbinned_array_pmf_data,

     save_binned_array_pmf_data,

     plot_binned_array_pmf_data)

+from genetic_algorithm_analysis import read_GA_results_messy

while this is technically an atomic commit, it doesn't functionally do anything, so this would typically be added elsewhere when this was needed

________________________________

In sensor_array/analysis/genetic_algorithm_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455439646>:

> +                temp_dict[gas] = float(row[gas])

+            comp_list.extend([temp_dict])

+

+    # Extracta  a list of all possible mol fractions for each individual gas

+    mole_fractions = {}

+    for gas in gases:

+        temp_list = []

+        for row in comp_list:

+            temp_list.extend([float(row[gas])])

+        temp_list_no_dups = list(set(temp_list))

+        temp_list_no_dups.sort()

+        mole_fractions[gas] = temp_list_no_dups

+    return comp_list, mole_fractions

+

+

+def moving_average_smooth(sim_results_import, mof_list, gases, comp_list, mole_fractions, num_points=1):

is this a duplicate of code elsewhere?

________________________________

In sensor_array/analysis/genetic_algorithm_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455843797>:

>

             # Update dictionary with pmf for each MOF

             new_temp_dict = []

             # Initialize the dictioary

             if mof_temp_dict == []:

                 for index in range(len(norm_probs_range)):

                     mof_temp_dict = all_results_sim[index].copy()

-                    mof_temp_dict.update({ 'PMF_Range' : norm_probs_range[index] })

-                    # mof_temp_dict.update({ 'PMF_Exact' : norm_probs_exact[index] })

+                    mof_temp_dict['PMF_Range'] = norm_probs_range[index]

+                    mof_temp_dict['PMF_Exact'] = norm_probs_exact[index]

outputting the range and the exact info doesn't look like it is part of "Added multiple error types for probability to GA code." should either be a separate commit or the commit message should include something about this.

________________________________

In sensor_array/analysis/execute_genetic_algorithm_analysis.py<https://github.com/WilmerLab/sensor_array_mof_adsorption/pull/19#discussion_r455845382>:

>

 # --------------------------------------------------

 # ----- Run the Genetic Algorithm ------------------

 # --------------------------------------------------



-array_size_vect = [10, 15, 20, 25, 30, 35, 40, 45]

-# array_size_vect = [1,2,3,4,5]

-num_runs = 3

+array_size_vect = [5, 10, 15, 20, 25, 30, 35, 40, 45]

+num_runs = 1

commit message is vague and doesn't indicate these changes to the runs / array_size_vect

________________________________

In sensor_array/helper/generate_compositions.py<https://github.com/WilmerLab/sensor_array_mof_ [...]

2020-07-20 18:59 UTC, paulboone approved these changes
I approve merging this under duress, knowing that we need to refactor a lot of this codebase.

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis_singlearray_allexp.py
> +import numpy as np
import is on line 66?

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/execute_brute_force_analysis_singlearray_allexp.py
> +    import numpy as np
also here

2020-07-20 18:59 UTC, paulboone commented on sensor_array/helper/generate_compositions.py
> -print('\nList of Compositions: \n', comp_list)
This commit is a mistake!

2020-07-20 18:59 UTC, paulboone commented on sensor_array/helper/generate_compositions.py
> +# breath_filepath = '/Users/brian_day/Desktop/HC_Work/breath-sample-results/'+type+'-samples/'
commented crap should  be removed

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/array_analysis_SVD.py
> +    MOF = re.sub(r'_v2', '', MOF)
pep8 variables

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/array_analysis_SVD.py
> +    MOF = re.sub(r'_eqeq', '', MOF)
shouldn't assign to an argument passed to a method, unless you intend the argument to be changed for caller.

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/array_analysis_SVD.py
> +
don't write your own file format!

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/array_analysis_SVD.py
> +
hard coded path

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/execute_sample_analysis.py
> +results_filepath = data['results_filepath']
could just use data straight

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/sample_analysis.py
> +
prediciton

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/sample_analysis.py
> +
prediciton

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/sample_analysis.py
> +
imports in the function? this implies the plots should be broken into a separate file

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/execute_sample_analysis.py
> +import sample_analysis as sa
sample analysis is a possible refactor target to pair

2020-07-20 18:59 UTC, paulboone commented on sensor_array/helper/execute_henrys_coefficient_analysis.py
> +# ----- Perform Analysis -----
bad commit, breaks the codebase

2020-07-20 18:59 UTC, paulboone commented on sensor_array/helper/henrys_coefficient_analysis.py
> +
if necessary and yaml doesn't have a way of doing this, then refactor into separate file for reuse

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/sample_analysis.py
> +def create_uniform_comp_list(gases, gas_limits, spacing, filename=None, imply_final_gas_range=True, imply_final_gas_spacing=False, filter_for_1=True, round_at=None):
This would be a rejected commit because it fixes problems that are not "real" and could be fixed with how you are running the code.

2020-07-20 18:59 UTC, paulboone commented on sensor_array/analysis/sample_analysis.py
> +
I don't like the name here because it is too generic and sounds already like np.linalg.inv

Can you just use pinv instead of this method?

2020-07-20 19:00 UTC, merged